### ISSUE TITLE
Request: Add *.tsx and *.jsx to lint extensions

### ISSUE THREAD

**Issue by favna** [discordjs/action-eslint#1]
I would like to run this action in a React based project so it would be nice if you could add the TSX and JSX extensions to the list of supported extensions. For now I forked the repo and use that but I would prefer to use the main project.

**Comment by iCrawl** [comment]
There's a few things here I should probably mention:

It is probably not needed anymore, as GitHub actions have their own built-in problem matcher for eslint properly working now. This comes with 2 distinct drawbacks:
- This action can't really "log" to the console properly anymore, because it would create annotations (which could be fine theoretically, but is currently creating duplicate annotations)
- PR annotations are not a thing if created with the API, but are very much so a thing when created with the problem matcher.

This made me rewrite my original version (this here is very much just a forked one) several times. I have not yet come up with a proper solution. I was experimenting with creating my own problem matcher with my own custom console output, so annotations get posted even on PRs, but this led to mostly issues with the formatting and how it didn't really look immensely better than just doing `eslint src/` yourself and let the standard GitHub actions problem matcher do its thing.

If you still want to use an updated version of this with more features:
https://github.com/iCrawl/action-eslint

**Comment by favna** [comment]
Tyvm for the swift reply, I'll be sure to look into that version. Closing this issue then.
